MyApp/urls.py
from django.urls import path
from MyApp import views as v

urlpatterns = [
    path('', v.index),
    path("enquiry/form/",v.enquiryForm,name="enquiry_form"),
    path("compare/price/",v.courier_list,name="compareCourierPrice")
]

courier_Compass/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from MyApp import urls as appUrl
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(appUrl))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyApp/models.py
from django.db import models

class ShipmentType(models.Model):
    typeName = models.CharField(max_length=100)
    def __str__(self):
        return self.typeName

class Courier(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='courier_images/')
    branch = models.CharField(max_length=100)
    serviceArea = models.ForeignKey('ServiceArea', related_name='couriers', on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class ServiceType(models.Model):
    typeName = models.CharField(max_length=100)
    def __str__(self):
        return self.typeName

class ServiceArea(models.Model):
    pincode = models.CharField(max_length=10)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zone = models.CharField(max_length=100)
    def __str__(self):
            return self.pincode

class TravelBy(models.Model):
    source = models.CharField(max_length=100, blank=False)
    def __str__(self):
        return self.source

class Users(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=100)

class EnquiryForm(models.Model):
    source_area = models.ForeignKey(ServiceArea, related_name='enquiry_source',on_delete=models.CASCADE)
    destination_area = models.ForeignKey(ServiceArea,related_name='enquiry_destination',on_delete=models.CASCADE)
    courierService = models.ForeignKey('Courier', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    serviceType = models.ForeignKey('ServiceType', on_delete=models.CASCADE)
    shipmentType = models.ForeignKey('ShipmentType', on_delete=models.CASCADE)
    TravelBy = models.ForeignKey('TravelBy', on_delete=models.CASCADE,blank=False)
    courierWght = models.CharField(max_length=100,default=0)

class CostTable(models.Model):
    courier = models.ForeignKey('Courier', on_delete=models.CASCADE)
    serviceType = models.ForeignKey('ServiceType', on_delete=models.CASCADE)
    shipmentType = models.ForeignKey('ShipmentType', on_delete=models.CASCADE)
    travelBy = models.ForeignKey('TravelBy', on_delete=models.CASCADE)
    from_weight_per_gram = models.DecimalField(max_digits=10, decimal_places=2)
    to_weight_per_gram = models.DecimalField(max_digits=10, decimal_places=2)
    localRate = models.DecimalField(max_digits=10, decimal_places=2)
    cityRate = models.DecimalField(max_digits=10, decimal_places=2)
    stateRate = models.DecimalField(max_digits=10, decimal_places=2)

MyApp/forms.py
from django import forms
from .models import *

class TravelByForm(forms.ModelForm):
    class Meta:
        model = TravelBy
        fields = '__all__'

class ShipmentTypeForm(forms.ModelForm):
    class Meta:
        model = ShipmentType
        fields = '__all__'

class CourierForm(forms.ModelForm):
    class Meta:
        model = Courier
        fields = '__all__'

class ServiceAreaForm(forms.ModelForm):
    class Meta:
        model = ServiceArea
        fields = '__all__'

class CostTableForm(forms.ModelForm):
    class Meta:
        model = CostTable
        fields = '__all__'

class ServiceTypeForm(forms.ModelForm):
    class Meta:
        model = ServiceType
        fields = '__all__'

class EnquiryDetailsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EnquiryDetailsForm, self).__init__(*args, **kwargs)
        self.fields['serviceType'].empty_label = None  # Corrected attribute name
        self.fields['shipmentType'].empty_label = None  # Corrected attribute name
        self.fields['source_area'].empty_label = "select by pin code ..."  # Corrected attribute name
        self.fields['destination_area'].empty_label = "select by pin code ..."  # Corrected attribute name
        self.fields['TravelBy'].empty_label = None  # Corrected attribute name
        
    class Meta:
        model = EnquiryForm
        fields = ['source_area', 'destination_area','serviceType','shipmentType', 'TravelBy', 'courierWght']
        labels = {
            'source_area': 'Source Area',
            'destination_area': 'Destination Area',
            'serviceType': 'Service Type',
            'shipmentType': 'Shipment Type',
            'TravelBy': 'Travel By',
            'courierWght': 'Courier Weight',
        }
        widgets = {
            'source_area': forms.Select(attrs={'class': 'form-control select2'}),
            'destination_area': forms.Select(attrs={'class': 'form-control select2'}),
            'serviceType': forms.Select(attrs={'class': 'form-control select2'}),
            'shipmentType': forms.Select(attrs={'class': 'form-control select2'}),
            'TravelBy': forms.Select(attrs={'class': 'form-control select2'}),
            'courierWght': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter courier weight'}),
        }

MyApp/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import *
from .forms import *

# Create your views here.
def index(request):
    return render(request,"index.html")
def enquiryForm(request):
    form = EnquiryDetailsForm(request.POST or None)
    
    return render(request, "enquiry.html",{"forms":form})

def courier_list(request):
    if request.POST:
        source_pincode = request.POST.get('source_area')
        destination_pincode = request.POST.get('destination_area')
        srvType = request.POST.get('serviceType')
        shipmentType = request.POST.get('shipmentType')
        courierTransp = request.POST.get('TravelBy')
        weight = int(request.POST.get('courierWght'))
        srv_data = ServiceType.objects.get(id = int(srvType))
        shp_data = ShipmentType.objects.get(id=int(shipmentType))
        trans_data = TravelBy.objects.get(id=int(courierTransp))
        data = CostTable.objects.filter(
            serviceType=srvType,
            travelBy=courierTransp,
            shipmentType=shipmentType,
            from_weight_per_gram__lte = weight,  # Less than or equal to the weight
            to_weight_per_gram__gte = weight 
        )
        source = ServiceArea.objects.filter(id=int(source_pincode)).last()
        destination = ServiceArea.objects.filter(id=int(destination_pincode)).last()
        for  i in data : 
            if source_pincode == destination_pincode:
                price = i.localRate
            elif source.state == destination.state and source.city == destination.city:
                price = i.cityRate
            elif source.state == destination.state and source.city != destination.city:
                price = i.stateRate
            else:
                price = i.stateRate + 50
            i.courier_cost = price

        filter_data = {
            "source" : f" {source.city} ({source.state})",
            "destination" : f" {destination.city} ({destination.state})",
            "weight" : f"{weight} Gram",
            "srvType" : srv_data.typeName,
            "shipmentType": shp_data.typeName,
            "transp": trans_data.source
        }

        return render(request, 'compareList.html', {'data': data,"filterData":filter_data})
    else:
        return redirect("enquiry_form")

MyApp/templates/compareList.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>Courier Details</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <style>
        .custom-logo {
            width: 65px;
            height: 65px; 
            max-width: 100px; 
            max-height: 100px; 
        }
        .card_container{
            overflow:auto;
        }
        .copyright {
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
        .header_bg{
            background-image: url("../../media/courier_images/headerImg.jpeg");
            background-size: cover;
            background-position: center;
            color: black;
            padding: 100px 0; 
            background-color: rgba(0, 0, 0, 0.5);
        }
    </style>
</head>
<body>
    <div class="jumbotron text-center header_bg">
        <h1 class="display-5">Find your best courier services</h1>
    </div>
    <div class="container mt-4 card_container">
        <div class="row">
            {% if filterData %}
                <div class="card mt-2" style="min-width: 100%;">
                    <div class="card-body text-center">
                        <h5 class="card-title">This result has been based on given input's</h5>
                    
                    </div>
                    <div class="row g-0">
                        <div class="col ml-5 d-flex align-items-left justify-content-left">
                            Source : {{filterData.source}}
                        </div>
                        <div class="col d-flex align-items-center justify-content-left">
                            Destination : {{filterData.destination}}
                        </div>
                        <div class="col d-flex align-items-center justify-content-left">
                            Service Type : {{filterData.srvType}}
                        </div>
                        
                    </div>
                    <div class="row g-0 mb-2">
                        <div class="col ml-5 d-flex align-items-center justify-content-left">
                            Courier Item : {{filterData.shipmentType}}
                        </div>
                        <div class="col d-flex align-items-center justify-content-left">
                            Shipment Mode : {{filterData.transp}}
                        </div>
                        <div class="col d-flex align-items-center justify-content-left">
                            Courier Weight: {{filterData.weight}}
                        </div>
                        
                    </div>
                </div>
            
            {% endif%}
        </div>
        <div class="row mb-2">
            {% for res in data %}
                <div class="card mt-2" style="min-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4 d-flex align-items-center justify-content-center">
                            <img src="{{ res.courier.image.url }}" class="card-img-top custom-logo" alt="{{ res.courier.name }}">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                            <h5 class="card-title">{{ res.courier.name }}</h5>
                            {% comment %} <p class="card-text">
                                This is a wider card with supporting text below as a natural lead-in 
                                to additional content. This content is a little bit longer.
                            </p>
                            <p class="card-text">
                                <small class="text-muted">Last updated 3 mins ago</small>
                            </p> {% endcomment %}
                            </div>
                        </div>
                        <div class="col-md-2 d-flex align-items-center justify-content-center">
                            Rs.<h3>{{ res.courier_cost }}</h3>
                        </div>
                    </div>
                </div>
            {% comment %} <div class="col">
                <div class="card">
                    <img src="{{ courier.image.url }}" class="card-img-top" alt="{{ courier.name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ courier.name }}</h5>
                        <p class="card-text">Source Area: {{ courier.serviceArea }}</p>
                        <p class="card-text">Destination Area: {{ courier.serviceArea }}</p>
                        <!-- You need to retrieve pricing information based on the courier -->
                        {% for cost_table in courier.costtable_set.all %}
                            {% if cost_table.serviceType == enquiry.serviceType and cost_table.shipmentType == enquiry.shipmentType and cost_table.travelBy == enquiry.travelBy %}
                                <p class="card-text">Price: {{ cost_table.cityRate }}</p>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div> {% endcomment %}
            {% endfor %}
        </div>
    </div>
    <div class="copyright">
        <p>&copy; 2024 Courier Cost Comparison</p>
    </div>
</body>
</html>

MyApp/templates/enquiry.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Enquiry Form</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"/>
    <style>

    body {
        background-color: #f2f2f2;
        padding-top: 20px;
      }
      .copyright {
        background-color: #333;
        color: #fff;
        padding: 10px 0;
        text-align: center;
        position: relative;
        bottom: 0;
        width: 100%;
      }
      .header_bg {
        background-image: url("../../media/courier_images/headerImg.jpeg");
        background-size: cover;
        background-position: center;
        color: black;
        padding: 70px 0;
        background-color: rgba(0, 0, 0, 0.2);
      }
    </style>
  </head>
  <body>
    <div class="jumbotron header_bg">
      <h1 class="display-5">Courier Service Enquiry Form</h1>
      <p class="lead">Please fill out the form below to get best deal.</p>
    </div>

    <div class="container">
      <form
        action="{% url 'compareCourierPrice' %}"
        method="POST"
        class="overflow-auto"
      >
        {% csrf_token %} {{forms.as_table}}
        <button type="submit" class="btn btn-primary form-control mt-2 md">
          Submit
        </button>
      </form>
    </div>
    <div class="copyright">
      <p>&copy; 2024 Courier Cost Comparison</p>
    </div>

    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/select2.min.js'%}"></script>
    <script>
      $(document).ready(function () {
        // Initialize Select2 for dropdowns
        $(".select2").select2();
      });
    </script>
  </body>
</html>

MyApp/templates/index.html
{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Welcome Page</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<style>
/* Custom styles */
body {
    background-color: #f2f2f2;
}
</style>
</head>
<body>

<div class="container text-center mt-5">
    <h1 class="display-4">Welcome to Our Website</h1>
    <p class="lead">We're glad to have you here!</p>
    <a class="btn btn-primary" href="{% url 'enquiry_form' %}">Get Started</a>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html> {% endcomment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Courier Cost Comparison</title>
    <style>
        /* Basic styles */
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            text-align: center;
        }
        .header {
            background-image: url("../../media/courier_images/welcome1.jpg");
            background-size: cover;
            background-position: center;
            color: #fff;
            padding: 200px 0; /* Adjust the padding to position the text */
        }
        h1 {
            font-size: 36px;
            margin-bottom: 20px;
        }
        p {
            font-size: 18px;
            margin-bottom: 20px;
        }
        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }
        .button:hover {
            background-color: #0056b3;
        }
        .copyright {
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
        /* Responsive design */
        @media screen and (max-width: 768px) {
            .header {
                padding: 80px 0; /* Adjust the padding for smaller screens */
            }
        }
    </style>
</head>
<body>
    <div class="header">
        
    </div>
    <div class="container">
        <h1>Welcome to Courier Cost Comparison</h1>
        <p>Compare costs from different courier services and choose the best option for your needs.</p>
        <a href="{% url 'enquiry_form' %}" class="button">Start Enquiry</a>
    </div>
    <div class="copyright">
        <p>&copy; 2024 Courier Cost Comparison</p>
    </div>
</body>
</html>